# Numpy Tutorial

# Single Dimensional Array

In [2]:
import numpy as np
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

# Multi Dimensional Array

In [20]:

n1=np.array([[10,20,30,40],[10,20,3,50]])
n1

array([[10, 20, 30, 40],
       [10, 20,  3, 50]])

In [18]:
#Initilizing Numpy array with zero

n1=np.ones((1,2))
n1

array([[1., 1.]])

In [19]:

n1=np.zeros((5,10))
n1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
#Initilizing Numpy array with same number
n1=np.full((3,3),10)
n1

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
#Initilizing Numpy array within a range
n1=np.arange(10,20)
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [26]:
#Initilizing Numpy array with skip value
n1=np.arange(10,50,5)
n1

array([10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
#Initilizing Numpy array with random number
n1=np.random.randint(1,10,3)
n1

array([6, 5, 3])

In [35]:
#checking the shape of Numpy array
n1=np.array([[1,2,3,5],[4,5,7,8]])
n1.shape

(2, 4)

In [40]:
n1.shape = (4,2)
n1

array([[1, 2],
       [3, 5],
       [4, 5],
       [7, 8]])

In [51]:
#vstack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [47]:
#hstack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [52]:
#column_stack()
n1=np.array([10,20,30])
n2=np.array([40,50,60])
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [56]:
#intersection and difference
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [62]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n1,n2)
#unique number n1 me Qki wo phele h 

array([10, 20, 30, 40])

In [65]:
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [68]:
#addition
n1=np.array([10,20])
n2=np.array([30,40])
np.sum([n1,n2],axis=0)

array([40, 60])

In [71]:
np.sum([n1,n2],axis=1)

array([30, 70])

In [72]:
np.sum([n1,n2])

100

In [74]:
#BAsic Addition
n1=np.array([10,20,30])
n1=n1+1
n1

array([11, 21, 31])

In [77]:
#Basic Multiplication
n1=np.array([10,20,30])
n1=n1*2
n1

array([20, 40, 60])

In [78]:
#Basic division
n1=np.array([10,20,30])
n1=n1/2
n1

array([ 5., 10., 15.])

In [79]:
# minus
n1=np.array([10,20,30])
n1=n1-4
n1

array([ 6, 16, 26])

In [84]:
#mean
n1=np.array([10,5,4,20,9,70])
np.mean(n1)

19.666666666666668

In [81]:
#standard deviation
np.std(n1)

23.098821518760552

In [82]:
#median
np.median(n1)

9.5

In [100]:
#numpy matrix
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
n1[1]

array([4, 5, 6])

In [90]:
n1[:,1]

array([2, 5, 8])

In [91]:
n1[:,2]

array([3, 6, 9])

In [97]:
n1[2,0]

7

In [98]:
#transposing values on matrix
n1.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [101]:
n1=np.array([[1,2,3],[4,5,6],[7,8,9]])
n2=np.array([[9,8,7],[6,5,4],[3,2,1]])
n1.dot(n2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [102]:
n2.dot(n1)

array([[ 90, 114, 138],
       [ 54,  69,  84],
       [ 18,  24,  30]])

In [106]:
#saving numpy
n1=np.array([10,20,30,40,50,60])
np.save('my_numpy.npy',n1)

In [107]:
n2=np.load('my_numpy.npy')
n2

array([10, 20, 30, 40, 50, 60])

In [108]:
n3=np.array([[10,20,30],[20,10,50]])
np.save('nump.npy',n3)

In [110]:
n4=np.load('nump.npy')
n4

array([[10, 20, 30],
       [20, 10, 50]])

In [7]:
#eye
import numpy as np
np.eye(4,3,dtype='i')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]], dtype=int32)

In [15]:
#arrange(start value, end value, step)
a= np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
np.arange

<function numpy.arange>

In [12]:
np.arange(-1,1,0.001)

array([-1.   , -0.999, -0.998, ...,  0.997,  0.998,  0.999])

In [17]:
#reshape
a.reshape((2,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [18]:
a.reshape((5,2))

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11],
       [13, 15],
       [17, 19]])

In [21]:
np.arange(20).reshape((2,2,5))

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])